### PR TITLE
Release 09.25.2021

### PR DESCRIPTION
**Pull request by tm2838**
## Description

Releasing more components update and functionality update.

- Related Products: dynamic comparison modal rendering, clicking on a product card navigates to the corresponding product
- Ratings and Reviews: actual star rating breakdown and product breakdown components in place, sorting & filtering reviews functionality, upload and display review photos

Implemented React Router and change request.
- clicking on a product card navigates to the corresponding product and fetches new product info, new related products and new reviews
- clicking anywhere on the page sends a post request to the `interaction` api, including the tagName of the element, the name (indicated by `id`) of the widget, and the time of that click.

### CODE REVIEW

**Review by surekhaw — APPROVED** [review]
Only detail I see that might be a little off is that the post to the interactions API contains the id of the widget, not the classname.

Otherwise, this is great!  I'm excited. :)

**Comment by tm2838** [comment]
> Only detail I see that might be a little off is that the post to the interactions API contains the id of the widget, not the classname.
> 
> Otherwise, this is great! I'm excited. :)

Yes you are right. I updated the description!

**Comment by surekhaw** [comment]
merged the error handling into dev. not sure if there should be a new commit to main?

**Comment by surekhaw** [comment]
🎇

**Pull request merged**
