### PR TITLE
Main image default view is mostly complete and functional

### PR DESCRIPTION
**Pull request by shabbyblue16**
## Description
The image gallery renders the default view of the main image, a column of thumbnail images, and navigational arrows. The navigational arrows function as specified in the Business Docs (left and right arrows changing the main image, up and down arrows changing the thumbnail images). Clicking on any of the thumbnail images renders that image as the main image. Css still needs polishing and expanded view functionality has not been implemented, but component is presentable and functional as is.

## How to test
Really procrastinating on writing unit tests so lets continue with the manual tests. How to test: open up the app in the browser, find the image gallery and click on all the things!

## Notes

- Component logic readability could use some work so definitely planning to refactor
- Some image urls coming from the Atelier api are bad, something to be mindful of
- Clicking on or navigating to images that have yet to render may take a few seconds to do so
- A couple small things (like underlining main image's corresponding thumbnail image) still need to be implemented
- Apologies for lumping a few tickets into one PR :/

## Issue tracking
https://trello.com/c/QXkVPbfs/44-m-create-main-image-component

### CODE REVIEW

**Comment by surekhaw** [comment]
Github is saying there are merge conflicts. Did you download the latest merges from dev?

**Comment by shabbyblue16** [comment]
Oops not yet, I’ll go ahead and do that

**Review by tm2838 — APPROVED** [review]
This is cool!

**Review by surekhaw — APPROVED** [review]
awesome!

**Pull request merged**
