### PR TITLE
Optimization

### PR DESCRIPTION
**Pull request by tm2838**
## Description

Bumping local SEO score.

## How to test

Run Lighthouse on local application (47421), SEO score should be improved from 67 to 97 (on my end, scores may differ)

## Notes

The changes in `package-lock.json` is probably due to me playing around with Brotli for text compression. Looks like it doesn't get along with my Ubuntu vm and I haven't been able to make it work there yet. So I removed the package for now.

### CODE REVIEW

**Review by surekhaw — COMMENTED** [review]
app crashed unless I installed multer. my performance went down to 55. review pics are not rendering. I got the following errors in the console:
GET c:\fakepath\yellow-shoes.jpeg net::ERR_UNKNOWN_URL_SCHEME
GET http://localhost:3000/product/47421/Submit 404 (Not Found)
GET http://localhost:3000/product/47421/sdfgsdfh 404 (Not Found)
GET http://localhost:3000/product/47421/adgdsg@email.com 404 (Not Found)

I believe the 404 errors might have to do with the text compression? I checked the network tab, and I saw under headers "Accept-encoding: gzip, deflate, br," and "content-type: text/html," but I did not see "content-encoding: br" (which should be there for brotli?)

I started from main. checkout out a new branch. pulled from dev. pulled from optimization. I confirmed that app.get for reviews was in the server.js. Am I missing a step?

**Comment by tm2838** [comment]
> app crashed unless I installed multer. my performance went down to 55. review pics are not rendering. I got the following errors in the console: GET c:\fakepath\yellow-shoes.jpeg net::ERR_UNKNOWN_URL_SCHEME GET http://localhost:3000/product/47421/Submit 404 (Not Found) GET http://localhost:3000/product/47421/sdfgsdfh 404 (Not Found) GET http://localhost:3000/product/47421/adgdsg@email.com 404 (Not Found)
> 
> I believe the 404 errors might have to do with the text compression? I checked the network tab, and I saw under headers "Accept-encoding: gzip, deflate, br," and "content-type: text/html," but I did not see "content-encoding: br" (which should be there for brotli?)
> 
> I started from main. checkout out a new branch. pulled from dev. pulled from optimization. I confirmed that app.get for reviews was in the server.js. Am I missing a step?

This is branched off of my previous branch which is currently merged to dev, `multer` was added for parsing image files, so yes, `npm install` is needed (https://github.com/The-Chonky-Panda/Atelier/pull/81)

The 404s I believe are for uploaded images? I noticed there are new reviews with images that cannot be loaded. If other people are uploading images and only using  `URL.createObjectURL()` to generate urls, the urls will start with `localhost` and cannot be loaded by other machines. So this is the error handling part. I think performance for other products should still be fine?

`Brotli` worked for me locally but not on my Ubuntu virtual machine yet. So I removed it when I opened this PR.

**Review by surekhaw — APPROVED** [review]
thank you for the clarification! BTW SEO went up to 100 for me :) (although performance is now only 58 :( )

**Comment by tm2838** [comment]
> thank you for the clarification! BTW SEO went up to 100 for me :) (although performance is now only 58 :( )

Yeah I think the 404s are causing the dropped performance. I'll probably need some error handling for that >_<

**Pull request merged**
