### PR TITLE
Submit review

### PR DESCRIPTION
**Pull request by tm2838**
## Description

Added the ability to post new request for a product.
Changed characteristics rating display in review modal to only display applicable characteristics (i.e. what's shown in product breakdown)
Added a validation framework to validate user input. Currently the style for each individual field hasn't work yet, failed validation would only display a message.

## How to test

1. switch between products and verify that in the write new review modal, characteristic rating only displays characteristics that are shown in product breakdown
2. fill out the review modal with invalid inputs (e.g, empty input for required fields, review body is less than 50 characters, email is not in the format of an email), and verify that on click 'submit review', the modal remains open, and on top of the modal a message in red shows up.
Screen Shot 2021-09-27 at 4 50 34 PM
3. fill out the review modal with valid inputs, and verify that on click 'submit review', the modal closes and review list is updated.

## Issue tracking

https://trello.com/c/RpIiO4L6

### CODE REVIEW

**Review by shabbyblue16 — APPROVED** [review]
Hey everything looks great as far as I can tell. That `reviewModal.jsx` file is a beast though, it was a little tricky keeping track of where I was as I was reading through. Great stuff as always though

**Comment by tm2838** [comment]
> Hey everything looks great as far as I can tell. That `reviewModal.jsx` file is a beast though, it was a little tricky keeping track of where I was as I was reading through. Great stuff as always though

Yeah I know, sorry about that lol. I may need to split it into smaller files if time allows.

**Comment by surekhaw** [comment]
@tm2838 I am having trouble getting it to accept my characteristics ratings. 
- I clicked add review
-  I clicked submit with everything blank (including characteristics)
- I partially filled everything out, including characteristics, but included less than 50 characters in the body. I received an error that the body and characteristics need to be filled out. (note the characteristics radio buttons were marked).
- I filled out the body with at least 50 characters
- I got an error to fill out characteristics
- I changed the characteristics by clicking a different set of radio buttons
- I still received an error to fill out characteristics
- I tried another set of radio buttons (meaning I clicked a different rating for each characteristic)
- still got the same error

am I misinterpreting the error message?

**Comment by tm2838** [comment]
> @tm2838 I am having trouble getting it to accept my characteristics ratings.
> 
> * I clicked add review
> * I clicked submit with everything blank (including characteristics)
> * I partially filled everything out, including characteristics, but included less than 50 characters in the body. I received an error that the body and characteristics need to be filled out. (note the characteristics radio buttons were marked).
> * I filled out the body with at least 50 characters
> * I got an error to fill out characteristics
> * I changed the characteristics by clicking a different set of radio buttons
> * I still received an error to fill out characteristics
> * I tried another set of radio buttons (meaning I clicked a different rating for each characteristic)
> * still got the same error
> 
> am I misinterpreting the error message?

oooo thank u for pointing it out! Yes that's a bug. The validation framework I built previously checks for all 6 characteristics which should not be the case. I commented it out for now.

**Pull request merged**
